### ISSUE TITLE
FR: Use both LibreLink and Diabox Apps at the same time.

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#10]
If both the LibreLink App and Diabox app can work in tandem, we would have best of both worlds. LibreLink will make it possible for great uploads to LibreView and LibreLinkUp apps to work (remote alerts, trend arrows, etc.). Currently only one app (last NFC scanned? Open/active app?) gets the scanned data.

**Comment by PieterDeBruijn** [comment]
Enabling Alerts, gives an error:
![Screenshot_20210302-104025](https://user-images.githubusercontent.com/3070301/109629125-cef32a80-7b43-11eb-885d-9e51fbfc158c.png)

**Comment by bubbledevteam** [comment]
It's a little strange that Libre2 would disconnect with Librelink when it was connected with DiaBox ,but sometimes it can be connected both with Librelink and DiaBox at the same time ,I need more time to figure out how to make 2 apps connected with it.

**Comment by PieterDeBruijn** [comment]
Please do not remove the LibreView Upload before fixing the LibreLink and Diabox tandem working correctly, or we will be impaired greatly in the usage.

**Comment by bubbledevteam** [comment]
> Please do not remove the LibreView Upload before fixing the LibreLink and Diabox tandem working correctly, or we will be impaired greatly in the usage.

We have to remove LibreView upload from DiaBox for Abbott is really  aggressive to it .DiaBox was removed from Testfight by Apple since we released that feature .And what was worse ,Abbott blocked people's LibreView when they found data was uploaded from DiaBox.

I will invest more time in making DiaBox and Librelink work at the same time

**Comment by rvilchez1** [comment]
Hi!
This feature is really useful for those needing to upload readings to LibreView at the same time we use Diabox. 
What's the status of the development? any candidate release for this?

Thanks a lot!
Ricardo

**Comment by bubbledevteam** [comment]
Technically it's impossible, for now Libre 2 protocol now has some authentications from the App side. .
