### ISSUE TITLE
BUG: settings not saved

### ISSUE THREAD

**Issue by Eddy69** [bubbledevteam/diabox#14]
In the for now latest version, the settings for Nightscout are not saved. Every time I change to another menu item, the settings are back to default.
For now, I fill in the settings and leave the app open at that page. That's not very practical if I want to see what happened overnight, for example.

**Comment by tobe-2k5** [comment]
i have the same issue

**Comment by PieterDeBruijn** [comment]
Did you both upgrade with nightscout enabled in the old version AND new version?

Does anyone have this bug with a clean install/configure?

**Comment by PieterDeBruijn** [comment]
Does downgrading offer a workable solution for now (until this has been fixed by the Diabox dev team)?

**Comment by 2fgcampjr** [comment]
Same issue. It always reverts to another NS URL and Key. Dont want to share that info in case it's someones actual working URL.

**Comment by tobe-2k5** [comment]
> Did you both upgrade with nightscout enabled in the old version AND new version?
> 
> Does anyone have this bug with a clean install/configure?

Yes. I upgraded the app with  NS enabled in the old/New Version
1. Download the News .APK Form GitHub
2. Install over the old diabox App and Upgrade

The NS that hardcoded in my diabox is https://re*******.ns.10be.de:**14/ --- i dont know If this Link is saved in all diabox apps? But i found the User at Facebook and she changed the ns i think

**Comment by 2fgcampjr** [comment]
> > Did you both upgrade with nightscout enabled in the old version AND new version?
> > Does anyone have this bug with a clean install/configure?
> 
> Yes. I upgraded the app with NS enabled in the old/New Version
> 
> 1. Download the News .APK Form GitHub
> 2. Install over the old diabox App and Upgrade
> 
> The NS that hardcoded in my diabox is https://re*******.ns.10be.de:**14/ --- i dont know If this Link is saved in all diabox apps? But i found the User at Facebook and she changed the ns i think

That's the same NS info in mine.

**Comment by Eddy69** [comment]
> Did you both upgrade with nightscout enabled in the old version AND new version?
> 
> Does anyone have this bug with a clean install/configure?

I had the issue with a clean install. I wanna keep this version on my phone, because of the override alarm volume feature. Just before sleep i correct the NS settings, so my arduino clock gets the correct bg values.
Btw: i have the same ns setting values, so they seem hardcoded.

**Comment by Eddy69** [comment]
I discovered late last night that my NS settings were correctly used, although the wrong settings were hardcoded and visible. But I'm very glad that I now have visible confirmation of those settings. So yeah, fixed.

**Comment by PieterDeBruijn** [comment]
Great to hear! Could you mark the ticket closed?

**Comment by Eddy69** [comment]
As this is resolved, the bug is closed 🔒 😊
