### ISSUE TITLE
BUG: Calibration on Bubble Mini 

### ISSUE THREAD

**Issue by majkeldzordan** [bubbledevteam/diabox#23]
Calibration does not work. I get an error that Libre 2 has not been connected for 5 minutes. But I'm using Libre 1 and it's connected all the time.

**Comment by bubbledevteam** [comment]
could you pls share a pic with log file ?

**Comment by PieterDeBruijn** [comment]
@majkeldzordan Any update?

**Comment by majkeldzordan** [comment]
Sorry, but they fixed xDrip+ for Bubble Mini in the meantime, so I uninstalled DiaBox already.

**Comment by PieterDeBruijn** [comment]
Ok, no problem. If you could close your tickets that would be great (so keep things cleaned up a bit).
