### ISSUE TITLE
Import does not restore data

### ISSUE THREAD

**Issue by uschindler** [bubbledevteam/diabox#24]
I had the impression that the import/export function is saving settings and collected data.

I restored a backup in my new phone. Unfortunately only settings were restored, but all measurements are lost.

I have them in libre view, but it is still bad that you can no longer display them in the app.

Please fix the export and import to work correct.

**Comment by PieterDeBruijn** [comment]
I can confirm this issue with version 2021-03-10 (current).

**Comment by uschindler** [comment]
Hi Pieter, thank you for confirming!

I keep the ZIP file backup. If this gets solved, I hope the old data can be *added* to data collected up to now. So restoring a backup should merge the data in (optionally) instead of replacing it.

In my case I had to delete the app from my phone (actually I did not restore on a new phone, but this is what people generally do).

**Comment by bubbledevteam** [comment]
> Hi Pieter, thank you for confirming!
> 
> I keep the ZIP file backup. If this gets solved, I hope the old data can be _added_ to data collected up to now. So restoring a backup should merge the data in (optionally) instead of replacing it.
> 
> In my case I had to delete the app from my phone (actually I did not restore on a new phone, but this is what people generally do).

I am sorry for it's a highly experimental feature and will be removed in next release , we will provide a DiaBox Follow feature which help to store and share data
