### ISSUE TITLE
BUG: import/export doesn't appear

### ISSUE THREAD

**Issue by Eddy69** [bubbledevteam/diabox#26]
After the update(s) (I got two 🤔) of today, import/export doesn't show in Settings>Integration.

**Comment by PieterDeBruijn** [comment]
Same here. It's gone ATM. Maybe needed some work as it only imported and exported setting, not the actual measurements (bug?).

**Comment by bubbledevteam** [comment]
will integrate some web service to generate reports and download data

**Comment by PieterDeBruijn** [comment]
Just my 2 cents: Exporting&importing setting would be nice to have though, eg. when resetting a device / moving to new phone. Especially the Bluetooth sync (key?) between the Libre2 and phone would be great to be able to move to a new device to keep a sensor working and not have to throw it away.

The data itself is always best to get to a Nightscout server, they are free to use, open source and lot's of people willing to help setup. So no big need to import/export any contents/data(base).
