### ISSUE TITLE
BUG: "extreme high" alarm without configuration options

### ISSUE THREAD

**Issue by Wolfgang511** [bubbledevteam/diabox#29]
I think there is an inconsistency in the alarm configuration in DiaBox:
You can set the limit values for 4 glucose level alarms, but can configure the alarm options for only 3 of them in "More Alerts":
High, Low and urgent low.
There are no possibilities to set snooze and sound options for the "extreme high" alarm.

**Comment by bubbledevteam** [comment]
It was removed in the middle 2020, I will refactor all alarm models as your email request.

**Comment by bubbledevteam** [comment]
Added in July's release
