### ISSUE TITLE
Since the last update, I can not receive data from Nightscout

### ISSUE THREAD

**Issue by cromys** [bubbledevteam/diabox#31]
Hi everyone, after updating I face a problem with the data sent to Nightscout, I check in Diabox and the connection is sucessful but Nightscout does not receive anything. Any help?
Thanks

**Comment by bubbledevteam** [comment]
better  check your Nightscount server

**Comment by ohrelyaurelie** [comment]
use http or https ?

**Comment by bubbledevteam** [comment]
> use http or https ?

https

**Comment by bubbledevteam** [comment]
> Hi everyone, after updating I face a problem with the data sent to Nightscout, I check in Diabox and the connection is sucessful but Nightscout does not receive anything. Any help?
> Thanks

need you to upload a log
Setting->About->Share Log

**Comment by PieterDeBruijn** [comment]
The URL should look like this:
https://yournighscoutname.herokuapp.com
Replace yournighscoutname with the name of you App.
You need the key to upload (secret API hash).
