### ISSUE TITLE
FR: same kind age notation in Details

### ISSUE THREAD

**Issue by Eddy69** [bubbledevteam/diabox#34]
I would like that the sensor age has the same format as the MaxSensorLife. It's more consistent and gives a better insight in age and lifetime.
![Screenshot_20210407-131310_DiaBox](https://user-images.githubusercontent.com/31344113/113862100-469e2000-97a8-11eb-8397-2a69ce180374.jpg)

**Comment by bubbledevteam** [comment]
Good Idea, will make it in next release

**Comment by bubbledevteam** [comment]
finished in DiaBox v8.4.2 & DiaBoxMe v1.6..9
