### ISSUE TITLE
LibreView Integration?

### ISSUE THREAD

**Issue by eselick** [bubbledevteam/diabox#36]
What has happened to the LibreView integration.? I'm not seeing it in the latest version V:2021.04.06.1. Are there plans to put it back? Thanks :-))

**Comment by bubbledevteam** [comment]
As I said many time, Abbott doesn't allow unauthorized data source upload data to its server, or they will suspend your LibreVeiw account.

What was worse ,Abbott reported to Apple and Google which make DiaBox was removed from App Store and GooglePlay, so let't stop this topic.

**Comment by eselick** [comment]
I'm a new user of the Bubblan Mini and also Diabox so I wasn't aware of the history here. What a shame and a disservice to the diabetic community by Abbott.
Thanks
