### ISSUE TITLE
Time interval in seconds isn't showing

### ISSUE THREAD

**Issue by Khaldoon1983** [bubbledevteam/diabox#41]
Hello, I have noticed the time interval that used to be counted down in seconds between received readings from FSL2 sensor isn't showing anymore, and Diabox isn't receiving the readings from the sensors spontaneously by Bluetooth, only via NFC scan, please help me on this issue
![Screenshot_20210518-132543_DiaBox](https://user-images.githubusercontent.com/84354109/118651194-2ddc4d80-b7dd-11eb-955d-e5ce672eec84.jpg)

**Comment by pmossie** [comment]
I seem to have the same issue after I started with a new sensor (FL2). Diabox doesn't want read it anymore automatically. Only manually scanning works. If I want to use the calibration option it saids that it hasn't connected. 

I am using the latest version v2021.04.29.1

It would be great if it worked again. It is a great app!

**Comment by Teddyy2** [comment]
I also have the same behaviour.

I can calibrate the sensor, but the interval is not showing and the automatical fetching of values is not working.

Also using version 2021.04.29.1

**Comment by q601180252** [comment]
need you to upload a log
Setting->About->Share Log

**Comment by bubbledevteam** [comment]
need you to upload a log
Setting->About->Share Log

**Comment by Teddyy2** [comment]
Hello,
you will find the log file in the attachments.I hope this helps.
Kind RegardsCelina


 
 
  Am Mo., Juli 5, 2021 at 5:33 schrieb ***@***.***>:   


need you to upload a log
Setting->About->Share Log

**Comment by bubbledevteam** [comment]
fixed in next release

**Comment by bubbledevteam** [comment]
fixed in July's release
