### ISSUE TITLE
Value jump after calibration initialization issues a rate alarm

### ISSUE THREAD

**Issue by Wolfgang511** [bubbledevteam/diabox#42]
May be only a minor bug, but:
When the calibration initialization phase is finished:
The next value is now computed by the calibration function. Depending on the sensor value and the calibration function a jump of the calibrated glucose value may occur. This jump may issue a rate alarm, if the alarm is configured and the jump exceeds the limit.

It may "cost" to much effort to avoid this little bug:
A. Detect the end of calibration initialization. In the next cycle disable the rate alarm check. But only for one cycle.
B. Detect the end of calibration initialization. In the next cycle apply the calibration function for the last cycle value which is used to compute the rate of glucose value. But only for one cycle.

Sorry, i don't know if the "Noise Estimate Correction" was On or Off when observing this behaviour.
Possibly this filter will prevent a jump after the end of calibration initializing.

**Comment by bubbledevteam** [comment]
Will fix it in next release
