### ISSUE TITLE
Some minor text issues

### ISSUE THREAD

**Issue by Wolfgang511** [bubbledevteam/diabox#47]
1. in the calibration graph display:
 "Offest" -> "Offset"
![grafik](https://user-images.githubusercontent.com/81721392/122388092-d4984300-cf6f-11eb-886f-a2b44acdaacb.png)

2. Disabling the Extreme Low alarm:
Set alarm sound to Off and Vibration to Off:
in the confirm dialog the "alarm name" is missing: "Extreme Low"
e.g. for the High alarm tne name is shown.
![grafik](https://user-images.githubusercontent.com/81721392/122388550-453f5f80-cf70-11eb-92cb-ce8c65bc66a8.png)

**Comment by PieterDeBruijn** [comment]
1. checked, but it's not in the translation files, so cannot be fixed via github (pull).
2. probably the same, looking for a non existant string is even harder :)

**Comment by Wolfgang511** [comment]
2. OK, thats right. Probably "in the near" of other "alarm names", but may be a missing string entry (and missing code ?).

**Comment by bubbledevteam** [comment]
fixs
![2E3BAD40A00A9B948B6F9B3F208C92EF](https://user-images.githubusercontent.com/53160423/124412649-924d6f00-dd81-11eb-96d2-6c9e70d325b4.jpg)
