### ISSUE TITLE
Dexcom login fails

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#48]
Going to "Settings", selecting "Follow Invitation", pushing "Dexcom" gives a login for (I guess Dexcom Share?). But the login fails for our (EU based) account:
![Screenshot_20210617-165002](https://user-images.githubusercontent.com/3070301/122425581-e1c52a00-cf8f-11eb-9cc3-59e82e0bef5e.png)
The login credentials are correct of course, but the login place might be geographically limited? Currently I can login on a webbrowser when going to this URL:
https://uam2.dexcom.com/identity/login?

Any succesfull Dexcom Share users?

**Comment by PieterDeBruijn** [comment]
When logged in, it uses the https://myaccount.dexcom.eu/ URL instead of a .com

**Comment by bubbledevteam** [comment]
This feature will be removed in next release

**Comment by PieterDeBruijn** [comment]
Ok, closing item then. Dexcom does have good and official API's to connect to, so some way for Diabox to work with them would be great.
