### ISSUE TITLE
Display of the HbA1c string on the main screen

### ISSUE THREAD

**Issue by Wolfgang511** [bubbledevteam/diabox#51]
A strongly shortened string "eA1C" is displayed for the HbA1c on the main screen, some users do not immediately understand this abbreviation.
Since it is an estimated or calculated HbA1c, the "e" is important.
Suggestion:
1. Display on the main screen "eHbA1c" and omission of the measuring method "NGSP%" or "IFCC".
The "NGSP" and "IFCC" measurement methods are directly linked to the units of measurement ("%" and "mmol / mol").
The unit of measurement is already displayed at the HbA1c value.

![HbA1c_Display_1](https://user-images.githubusercontent.com/81721392/122775798-ccf7d780-d2aa-11eb-9558-8b31dec21a80.jpg)

2. For this you should formulate a little more precisely in the settings for the eHbA1c:
On the left either "eHbA1c" or "estimated HbA1C" (if the field width is sufficient).
In the selection list, specify the measurement method with the unit of measurement "NGSP (%)" and "IFCC (mmol / mol)".
Maybe the width of the entries in the list control has to be adjusted? 

![HbA1c_Conf_1](https://user-images.githubusercontent.com/81721392/122776004-fdd80c80-d2aa-11eb-9bda-e73025dd39cc.jpg)

**Comment by bubbledevteam** [comment]
![image](https://user-images.githubusercontent.com/53160423/124085585-c889a680-da82-11eb-9e30-d609c5f52b33.png)
![image](https://user-images.githubusercontent.com/53160423/124085658-d8a18600-da82-11eb-802c-54651298c657.png)
![image](https://user-images.githubusercontent.com/53160423/124085692-e35c1b00-da82-11eb-8c65-0f1e9aae3997.png)

**Comment by bubbledevteam** [comment]
I think it would ok this way

**Comment by bubbledevteam** [comment]
fixed
