### ISSUE TITLE
Add Standard Deviation metric

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#54]
Dexcom and others display the metric: SD (standard deviation). It says a lot about the distribution of glucose levels and would be very nice to see:
![Clarity](https://user-images.githubusercontent.com/3070301/123926591-4dde5f80-d98c-11eb-8c65-b7616ee7c334.png)

This metric can be easily added next to "Time in Range" an eA1C numbers.

**Comment by bubbledevteam** [comment]
fixs
![Screenshot_20210705_111155_com outshineiot diabox](https://user-images.githubusercontent.com/53160423/124412817-ef492500-dd81-11eb-8a82-b124fa0fd97f.jpg)
