### ISSUE TITLE
PR: values all over the place

### ISSUE THREAD

**Issue by Eddy69** [bubbledevteam/diabox#57]
It looks like the new algorithm makes the values all over the place. In relation to that, the value of the choosen measure bullet gets unreadable to the right.
![Screenshot_20210803-122712_DiaBox](https://user-images.githubusercontent.com/31344113/128000860-1b44d732-9134-4745-a2cd-041cfa1c83e0.jpg)
(edit: better screenshot)

**Comment by bubbledevteam** [comment]
Will fix in next release
