### ISSUE TITLE
BUG: App crashing (Android)

### ISSUE THREAD

**Issue by nupurlalvani** [bubbledevteam/diabox#58]
![Screenshot_20210811-200843__01](https://user-images.githubusercontent.com/54399465/129053907-71fb0caf-bb7a-45cf-9d55-6d5013d668a0.jpg)
![Screenshot_20210811-203023__01](https://user-images.githubusercontent.com/54399465/129053913-d256ba8d-2b45-4e58-9401-574c21c378a7.jpg)

App crashes when trying to open, version Diabox_2021-08-02.apk (screenshot attached w Android version etc). The previous released version doesn't re-initiate the Libre Pro (screenshot attached). Not sure if I'm doing something wrong? I've granted all permissions & allowed it to download and modify the app in Settings.

**Comment by bubbledevteam** [comment]
This will be fixed in next release
