### ISSUE TITLE
No landscape chart (graphic zoom) for historical data.

### ISSUE THREAD

**Issue by Wolfgang511** [bubbledevteam/diabox#60]
EPrerelease version DiaBox_2021.08.09.1 

If one selects  historical data with the date picker and then switches to the new landscape mode, the actual data are shown, not the day in the past.
If one switches back to normal view, the day in the past is shown.
That is a little bit confusing.
I would expect that the landscape chart also shows the data of the past. 

B. If the landscape view works also with historical data:
A navigation with e.g. forward/backwards arrows to go one day forward resp. backwards would be preferable see issue #59 

But that may conflict with the range selection by tapping in the header line.

**Comment by bubbledevteam** [comment]
fixed in issue https://github.com/bubbledevteam/diabox/issues/59
