### ISSUE TITLE
FR: Auto language setting

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#7]
It would be great to have this setting be correct, directly from the start. You can know the users language setting by way of the OS settings. Great to have a way to change this, so please do not remove the manual override. But great settings from the start offer a better experience, and have less user input (always better).

Please provide a way to offer extra translations. Internationalization is always a good thing. I would be more than willing to help with the Dutch translation.

**Comment by bubbledevteam** [comment]
thanks your advices

I will upload all translation files on github later

**Comment by PieterDeBruijn** [comment]
Just checked, latest release seems to fix the default language selection! Great! Thanks!

Updated several languages (SE, NL also included). Closing this ticket.
