### ISSUE TITLE
UI: Switch date by pressing date (remove edit icon)

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#8]
I would like to propose some UI changes, to simplify the daily usage. To start maybe switch dates, by pressing the date itself and remove the edit icon. This is maybe a small change, but older data is less important (still very nice to have). Ticking the date itself is intuative enough.

**Comment by bubbledevteam** [comment]
Will do

**Comment by PieterDeBruijn** [comment]
Implemented. Closing ticked.
