### ISSUE TITLE
BUG: Trend arrows missing in push data to LibreView Upload (LibreLink)

### ISSUE THREAD

**Issue by PieterDeBruijn** [bubbledevteam/diabox#9]
The trend indicators (arrows), are always horizontal, indicating a stable outlook. Diabox has the correct trends, but does not (correctly) send them to LibreView.

**Comment by PieterDeBruijn** [comment]
See for example all the trend arrows (they should not be all stable/the same):
![Screenshot_20210302-103748](https://user-images.githubusercontent.com/3070301/109628766-6c019380-7b43-11eb-9c2f-1675d861c0fb.png)

**Comment by bubbledevteam** [comment]
Better with DiaBox version 

If I was not wrong I think you are on the version which supports LibreView upload, for Abbott's attitude,I don't recommend you upload data to Libreview from DiaBox ,and this feature is disabled in newer versions

**Comment by PieterDeBruijn** [comment]
Ok, of the LibreLink app can upload to LibreView en LibreLinkUp, improving the upload from within Diabox seems redundant indeed. Closing this bug.
